### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by Merith-TK** [ArisuOngaku/aur-caddy#8]
https://caddy.community/t/v2-archlinux-aur-unable-to-build-and-install-caddy-v2/9528 < see here for build logs

Okay mini rant, sorry if this part is agressive
Please for the love of god provide a `-bin` version of this, not everyone has time to spend compiling and downloading toolchains just to run a simple webserver, i cant even install it because of a error that i have no clue what the hell it means, so please. provide a binary repo or rename this one to have `-git` on the aur, having to run caddy through docker is not exactly the preferred way of doing things with caddyserver,

**Comment by Merith-TK** [comment]
Im even willing to work on making a PKGBUILD (once i learn how they work) to download the latest release they have from github and install it

**Comment by ashpieboop** [comment]
Hi,

If you want to create a `caddy2-bin` aur package, please feel free to do so.

My understanding is that `-git` packages are packages that both pull their sources from a git repo and automatically get the latest commit without PKGBUILD modification needed. This package (`caddy2`) pins the source repository to stable release tags which excludes it from this definition.

Furthermore, the official `caddy` package's [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/caddy/trunk/next/PKGBUILD) on `next` does work that way, pulling caddy's git repo and pinning to stable release tags.

If the official `caddy` package ever chose to to distribute official binaries instead of a custom compiled one, the `caddy2` aur package would still have to work that way because distributing binaries on an aur package means it has to be suffixed with `-bin` (per [the AUR submission guidelines wiki page](https://wiki.archlinux.org/index.php/AUR_submission_guidelines#Rules_of_submission)).

I would be happy to help you with your compilation errors, however please provide a full log of the build **without any modification of the `PKGBUILD`**. Please also note that caddy 2.1.2 (latest stable version) doesn't build with go 1.15 (current official arch `go` package version) so please stay with go 1.14 for now.

**Comment by ashpieboop** [comment]
I'm closing this issue, but feel free to reply and I'll reopen it.
